# Import

Im ersten Teil des Feature Engineerings wird die grundlegende Struktur des vorliegenden Datensatzes sorgfältig überprüft, einschließlich der Anzahl der Zeilen und Spalten, der NaN-Werte und der Datentypen. Es ist entscheidend, ein erstes Verständnis für den Umfang der behandelten Daten zu haben.

In [ ]:
import pandas as pd #Datenanalyse und -manipulation

In [5]:
cars_df = pd.read_csv("German_Cars_Data.csv", sep=";")
cars_df  = cars_df .drop("Unnamed: 0", axis= 1) #Unbekannte Modelle fallen lassen
cars_df = cars_df.copy()

<ipython-input-5-23d3e04eb8fb>:1: DtypeWarning: Columns (79,82,85) have mixed types. Specify dtype option on import or set low_memory=False.
  cars_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Business Analytics/Project/data/final/German_Cars_Data.csv", sep=";")

In [6]:
cars_df.head()

,url,Country,Date,Marke,Modell,Barzahlungspreis,Anzahlung,Laufzeit,Nettodarlehen,Effektiver Jahreszins,...,Elektrische Reichweite (WLTP),Stromverbrauch (WLTP)2,Elektrische Reichweite7,"€ 3.000,-","€ 4.500,-",Elektrische Reichweite (WLTP)7,"€ 3.500,-","€ 5.500,-","€ 2.400,-","€ 5.000,-"
0,/angebote/volkswagen-181-zivile-ausfuehrung-gu...,Deutschland,2023-12-10 12:09:28.327713,volkswagen,181,29181.0,"€ 0,-",60 Monate,"€ 29.181,-","5,68 %",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,/angebote/volkswagen-181-kuebel-benzin-rot-e45...,Deutschland,2023-12-10 12:09:28.819334,volkswagen,181,11495.0,"€ 0,-",60 Monate,"€ 11.495,-","5,68 %",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,/angebote/volkswagen-181-benzin-gruen-c47cf7af...,Deutschland,2023-12-10 12:09:29.293417,volkswagen,181,9500.0,"€ 0,-",60 Monate,"€ 9.500,-","5,68 %",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,/angebote/volkswagen-181-kuebelwagen-the-thing...,Deutschland,2023-12-10 12:09:30.341151,volkswagen,181,8400.0,"€ 0,-",36 Monate,"€ 8.400,-","5,68 %",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,/angebote/volkswagen-181-vw-kuebel-typ-82-benz...,Deutschland,2023-12-10 12:09:30.967970,volkswagen,181,65000.0,"€ 0,-",48 Monate,"€ 65.000,-","5,99 %",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
cars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91398 entries, 0 to 91397
Data columns (total 89 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   url                             91398 non-null  object
 1   Country                         91398 non-null  object
 2   Date                            91398 non-null  object
 3   Marke                           91398 non-null  object
 4   Modell                          91398 non-null  object
 5   Barzahlungspreis                82387 non-null  float64
 6   Anzahlung                       91336 non-null  object
 7   Laufzeit                        91336 non-null  object
 8   Nettodarlehen                   82387 non-null  object
 9   Effektiver Jahreszins           82387 non-null  object
 10  Sollzins geb. p.a.              82387 non-null  object
 11  Monatliche Rate                 91336 non-null  object
 12  Karosserieform                  91398 non-null  object
 13  Fahrzeugart                     91398 non-null  object
 14  Sitzplätze                      87969 non-null  float64
 15  Türen                           90150 non-null  float64
 16  Länderversion                   47304 non-null  object
 17  Kilometerstand                  91197 non-null  object
 18  Erstzulassung                   87540 non-null  object
 19  Leistung                        91288 non-null  object
 20  Getriebe                        90721 non-null  object
 21  Hubraum                         83974 non-null  object
 22  Kraftstoff                      81930 non-null  object
 23  Umweltplakette                  70598 non-null  object
 24  Komfort                         89268 non-null  object
 25  Außenfarbe                      89731 non-null  object
 26  Farbe laut Hersteller           68414 non-null  object
 27  Innenausstattung                81351 non-null  object
 28  Überführungskosten              90847 non-null  object
 29  Zulassungskosten                90847 non-null  object
 30  Gesamt, einmalig                90847 non-null  object
 31  Leasinggesamtbetrag             50819 non-null  object
 32  Vertragsart                     90847 non-null  object
 33  Fahrleistung p.a.               90847 non-null  object
 34  Leasingfaktor                   39759 non-null  object
 35  Mehr-km Kosten                  71782 non-null  object
 36  Minder-km Vergütung             80745 non-null  object
 37  Preis                           91398 non-null  float64
 38  Ort                             91398 non-null  object
 39  Antriebsart                     57816 non-null  object
 40  Fahrzeughalter                  67616 non-null  float64
 41  Gänge                           44884 non-null  float64
 42  Zylinder                        50113 non-null  float64
 43  Leergewicht                     50578 non-null  object
 44  Lackierung                      74129 non-null  object
 45  HU                              72824 non-null  object
 46  Schlussrate                     48724 non-null  object
 47  Scheckheftgepflegt              62932 non-null  object
 48  Nichtraucherfahrzeug            63973 non-null  object
 49  Letzte Inspektion               10661 non-null  object
 50  Extras                          88288 non-null  object
 51  Farbe der Innenausstattung      78251 non-null  object
 52  Unterhaltung/Media              86995 non-null  object
 53  Angebotsnummer                  54438 non-null  object
 54  Schlüsselnummer                 44550 non-null  object
 55  Baujahr                         18256 non-null  float64
 56  Kraftstoffverbrauch2            61219 non-null  object
 57  CO₂-Emissionen2                 58023 non-null  object
 58  Energieeffizienzklasse          23155 non-null  object
 59  CO₂-Effizienz                   23155 non-null  object
 60  Schadstoffklasse                68742 non-null  object
 61  Sicherheit                      88761 non-null  object
 62  Garantie                        35645 non-null  object
 63  Kraftstoffverbrauch (WLTP)2     11130 non-null  object
 64  CO₂-Emissionen (WLTP)2          14823 non-null  object
 65  Bruttodarlehensbetrag           10291 non-null  object
 66  Bearbeitungsgebühren            10291 non-null  object
 67  Fahrzeugzustand                 2753 non-null   object
 68  Verfügbar ab                    1397 non-null   object
 69  Verfügbarkeit                   828 non-null    object
 70  Letzter Zahnriemenwechsel       1471 non-null   object
 71  Sonderzahlung                   1851 non-null   object
 72  Taxi oder Mietwagen             1865 non-null   object
 73  € 0,-                           0 non-null      float64
 74  Andere Energieträger            10337 non-null  object
 75  Elektrische Reichweite          1291 non-null   object
 76  Stromverbrauch2                 2467 non-null   object
 77  Batteriebesitz                  723 non-null    object
 78  Ladezeit von 10% bis 80%        615 non-null    object
 79  Elektrische Reichweite (WLTP)   4102 non-null   object
 80  Stromverbrauch (WLTP)2          4181 non-null   object
 81  Elektrische Reichweite7         639 non-null    object
 82  € 3.000,-                       0 non-null      float64
 83  € 4.500,-                       0 non-null      float64
 84  Elektrische Reichweite (WLTP)7  7 non-null      object
 85  € 3.500,-                       0 non-null      float64
 86  € 5.500,-                       0 non-null      float64
 87  € 2.400,-                       0 non-null      float64
 88  € 5.000,-                       0 non-null      float64
dtypes: float64(15), object(74)
memory usage: 62.1+ MB

In [9]:
# die features und ihren Datentyp verstehen, NaN prüfen

info_df = pd.DataFrame({
    'Column': cars_df.columns,
    'Non-Null Count': cars_df.count().values,
    'Dtype': cars_df.dtypes.values
})


info_df

                            Column  Non-Null Count    Dtype
0                              url           91398   object
1                          Country           91398   object
2                             Date           91398   object
3                            Marke           91398   object
4                           Modell           91398   object
..                             ...             ...      ...
84  Elektrische Reichweite (WLTP)7               7   object
85                       € 3.500,-               0  float64
86                       € 5.500,-               0  float64
87                       € 2.400,-               0  float64
88                       € 5.000,-               0  float64

[89 rows x 3 columns]

# Feature Reduktion

Im folgenden werden wir unnötige Features löschen. Dies sind vor allem Features, die zu viele NaN-Werte haben, im Falle eine Vorhersage nicht vorhanden wären oder zu viele unterschiedliche Ausprägungen haben (Individualität).

In [59]:
cars_df["Karosserieform"].value_counts()

Limousine                  24500
SUV/Geländewagen/Pickup    21969
Coupé                      11995
Kombi                      11214
Van/Kleinbus               10482
Cabrio                      7064
Kleinwagen                  2566
Sonstige                    1097
Transporter                  511
Name: Karosserieform, dtype: int64

In [12]:
info_df[["Column", "Non-Null Count"]].sort_values(by="Non-Null Count")

         Column  Non-Null Count
88    € 5.000,-               0
86    € 5.500,-               0
85    € 3.500,-               0
83    € 4.500,-               0
82    € 3.000,-               0
..          ...             ...
38          Ort           91398
37        Preis           91398
13  Fahrzeugart           91398
4        Modell           91398
0           url           91398

[89 rows x 2 columns]

In [63]:
interessante_features = ["url",
"Date",
"Country",
"Marke",
"Modell",
"Ort",
"Preis",
"Fahrzeugart",
"Karosserieform",
"Leistung",
"Kilometerstand",
"Fahrleistung p.a.",
"Getriebe",
"Türen",
"Außenfarbe",
"Komfort",
"Sicherheit",
"Extras",
"Sitzplätze",
"Erstzulassung",
"Unterhaltung/Media",
"Hubraum",
"Kraftstoff",
"Innenausstattung",
"Farbe der Innenausstattung",
"Umweltplakette",
"Schadstoffklasse",
"Fahrzeughalter",
"Nichtraucherfahrzeug",
"Scheckheftgepflegt",
"Kraftstoffverbrauch2",
"CO₂-Emissionen2",
"Antriebsart",
"Leergewicht",
"Zylinder",
"Länderversion",
"Gänge",
"Garantie",
"Energieeffizienzklasse",
"Baujahr",
"CO₂-Emissionen (WLTP)2",
"Kraftstoffverbrauch (WLTP)2",
"Letzte Inspektion",
"Elektrische Reichweite (WLTP)",
"Fahrzeugzustand",
"Taxi oder Mietwagen"]

In [64]:
# die interessanten Variablen auswählen 
# und einen Datenrahmen nur mit ihnen erstellen
cars_df = cars_df[interessante_features]

In [65]:
cars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91398 entries, 0 to 91397
Data columns (total 46 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   url                            91398 non-null  object
 1   Date                           91398 non-null  object
 2   Country                        91398 non-null  object
 3   Marke                          91398 non-null  object
 4   Modell                         91398 non-null  object
 5   Ort                            91398 non-null  object
 6   Preis                          91398 non-null  float64
 7   Fahrzeugart                    91398 non-null  object
 8   Karosserieform                 91398 non-null  object
 9   Leistung                       91288 non-null  object
 10  Kilometerstand                 91197 non-null  object
 11  Fahrleistung p.a.              90847 non-null  object
 12  Getriebe                       90721 non-null  object
 13  Türen                          90150 non-null  float64
 14  Außenfarbe                     89731 non-null  object
 15  Komfort                        89268 non-null  object
 16  Sicherheit                     88761 non-null  object
 17  Extras                         88288 non-null  object
 18  Sitzplätze                     87969 non-null  float64
 19  Erstzulassung                  87540 non-null  object
 20  Unterhaltung/Media             86995 non-null  object
 21  Hubraum                        83974 non-null  object
 22  Kraftstoff                     81930 non-null  object
 23  Innenausstattung               81351 non-null  object
 24  Farbe der Innenausstattung     78251 non-null  object
 25  Umweltplakette                 70598 non-null  object
 26  Schadstoffklasse               68742 non-null  object
 27  Fahrzeughalter                 67616 non-null  float64
 28  Nichtraucherfahrzeug           63973 non-null  object
 29  Scheckheftgepflegt             62932 non-null  object
 30  Kraftstoffverbrauch2           61219 non-null  object
 31  CO₂-Emissionen2                58023 non-null  object
 32  Antriebsart                    57816 non-null  object
 33  Leergewicht                    50578 non-null  object
 34  Zylinder                       50113 non-null  float64
 35  Länderversion                  47304 non-null  object
 36  Gänge                          44884 non-null  float64
 37  Garantie                       35645 non-null  object
 38  Energieeffizienzklasse         23155 non-null  object
 39  Baujahr                        18256 non-null  float64
 40  CO₂-Emissionen (WLTP)2         14823 non-null  object
 41  Kraftstoffverbrauch (WLTP)2    11130 non-null  object
 42  Letzte Inspektion              10661 non-null  object
 43  Elektrische Reichweite (WLTP)  4102 non-null   object
 44  Fahrzeugzustand                2753 non-null   object
 45  Taxi oder Mietwagen            1865 non-null   object
dtypes: float64(7), object(39)
memory usage: 32.1+ MB

In [66]:
cars_df.to_csv('Zwischenspeicher_Cars_Data.csv', index=True,  sep=";")

Ideen:

- Erstzulassung anstatt Baujahr
- Bei Sicherheit, Komfort etc. mit Anzahl an Buchstaben in eine Skala einteilen
- Bei Fahrzeugzustand, für alle anderen Fahrzeuge nicht Unfallfahrzeug, fahrtauglich angeben